export const PROCESS_MAPPINGS = [
  { "p": "NPD Register", "id": "DD/R/010", "dept": "design" },
  { "p": "Master Piece", "id": "DD/R/008", "dept": "design" },
  { "p": "Product Validation Report", "id": "DD/R/014", "dept": "design" },
  { "p": "NPD Proto Model", "id": "DD/R/012", "dept": "design" },
  { "p": "Product List", "id": "DD/R/001", "dept": "design" },
  { "p": "Product Drawing Control", "id": "DD/R/004", "dept": "design" },
  { "p": "Bill of Materials - BOM", "id": "DD/R/002", "dept": "design" },
  { "p": "Revision Control", "id": "DD/R/005", "dept": "design" },
  { "p": "Product Revision", "id": "DD/R/006", "dept": "design" },
  { "p": "Product Success Rate", "id": "DD/R/007", "dept": "design" },
  { "p": "Product Sample List", "id": "DD/R/011", "dept": "design" },
  { "p": "Technical Specification", "id": "DD/R/003", "dept": "design" },
  { "p": "Production Plan", "id": "MR/R/001", "dept": "production" },
  { "p": "Production Report", "id": "MR/R/002", "dept": "production" },
  { "p": "Rejection Report", "id": "MR/R/003", "dept": "production" },
  { "p": "Dispatch", "id": "MR/R/006", "dept": "production" },
  { "p": "Shift Schedule", "id": "MR/R/007", "dept": "production" },
  { "p": "Quality Audits", "id": "QA/F/005", "dept": "quality" },
  { "p": "Instruments", "id": "QA/R/001", "dept": "quality" },
  { "p": "Instrument & Calibration", "id": "QA/R/002", "dept": "quality" },
  { "p": "Incoming Inspection", "id": "QA/R/003", "dept": "quality" },
  { "p": "Customer Complient Register", "id": "QA/R/007", "dept": "quality" },
  { "p": "Process Control Plan", "id": "QA/R/009", "dept": "quality" },
  { "p": "Certificate Renewal", "id": "QA/R/011", "dept": "quality" },
  { "p": "Continous Improvement", "id": "MR/R/005", "dept": "production" },
  { "p": "Rework Report", "id": "MR/R/003A", "dept": "production" },
  { "p": "Machine List", "id": "MN/R/001", "dept": "maintainance" },
  { "p": "Machine History Card", "id": "MN/R/002", "dept": "maintainance" },
  { "p": "Preventive Maintenance", "id": "MN/R/003", "dept": "maintainance" },
  { "p": "KWH Monitoring", "id": "MN/R/005", "dept": "maintainance" },
  { "p": "Customer List", "id": "MS/R/004", "dept": "sales" },
  { "p": "Quotation List", "id": "MS/R/005", "dept": "sales" },
  { "p": "Order List", "id": "MS/R/006", "dept": "sales" },
  { "p": "Product Sample Register", "id": "MS/R/002", "dept": "sales" },
  { "p": "Customer Trail", "id": "MS/R/001", "dept": "sales" },
  { "p": "Item List", "id": "PR/R/002", "dept": "purchase" },
  { "p": "Vendor List", "id": "PR/R/001", "dept": "purchase" },
  { "p": "Procurement Register", "id": "PR/R/003", "dept": "purchase" },
  { "p": "Store Register", "id": "ST/R/005", "dept": "stores" },
  { "p": "Stock Data", "id": "ST/R/006", "dept": "stores" },
  { "p": "Employee History", "id": "HR/R/001", "dept": "hr" },
  { "p": "Attendance Register", "id": "HR/R/002", "dept": "hr" },
  { "p": "Training Schedule", "id": "HR/R/003", "dept": "hr" },
  { "p": "Safety Follow Ups", "id": "HR/R/008", "dept": "hr" },
  { "p": "5s", "id": "HR/R/007", "dept": "hr" },
  { "p": "Skill Matrix", "id": "HR/R/005", "dept": "hr" },
  { "p": "Field Visit Report", "id": "MS/R/003", "dept": "sales" },
  { "p": "Product Revision", "id": "DD/R/006", "dept": "design" },
  { "p": "RC STATUS", "id": "DD/R/005A", "dept": "design" },
  { "p": "Products", "id": "DD/R/002A", "dept": "design" },
  { "p": "Settings", "id": "MR/R/002A", "dept": "production" },
  { "p": "Break Hour", "id": "MR/R/002B", "dept": "production" },
  { "p": "Action Taken", "id": "MR/R/003B", "dept": "production" },
  { "p": "Quality Inspection", "id": "QA/R/003A", "dept": "quality" },
  { "p": "Action Plan", "id": "QA/R/007A", "dept": "quality" },
  { "p": "Continous Improvement Status", "id": "MR/R/005A", "dept": "production" },
  { "p": "AUDIT", "id": "QA/F/005A", "dept": "quality" },
  { "p": "Inward", "id": "PR/R/003A", "dept": "purchase" },
  { "p": "Dockets", "id": "MS/R/006A", "dept": "sales" },
  { "p": "Calibration Details", "id": "QA/R/002A", "dept": "quality" },
  { "p": "Certificate Renewal Details", "id": "QA/R/011A", "dept": "quality" }
];
